### PR TITLE
Upgrade Node to 20.x

### PR DESCRIPTION
**Pull request by Arnold-Nkamdem**

### CODE REVIEW

**Comment by markhobson** [comment]
Thanks @Arnold-Nkamdem!

**Comment by Arnold-Nkamdem** [comment]
You're welcome Mark Hobson!

**Comment by Arnold-Nkamdem** [comment]
> Thanks @Arnold-Nkamdem!

@markhobson can you push it on Docker Hub, please?

**Comment by markhobson** [comment]
I tried running the demo against the new image and it fails due to Chrome/ChromeDriver version mismatch. That really needs addressing first before pushing to Docker Hub. Unfortunately that problem is due to Protractor now being unsupported, and I ran out of time investigating how best to replace it.

**Comment by Arnold-Nkamdem** [comment]
Ahh, okay. I understood.
Please let me know when you resolved it.

**Comment by markhobson** [comment]
I've raised #16 for the Protractor issue. Not sure how much time I'll have to look at this, so thoughts welcome!

**Comment by Arnold-Nkamdem** [comment]
Okay

**Comment by markhobson** [comment]
@Arnold-Nkamdem Fixed and pushed to DockerHub :)

**Comment by Arnold-Nkamdem** [comment]
> @Arnold-Nkamdem Fixed and pushed to DockerHub :)

Okay, thank you @markhobson

**Pull request merged**
